module.exports = {
    Avatar: require('./avatar.js'),
    Furry: require('./furry.js'),
    Gay: require('./gay.js'),
    Help: require('./help.js'),
    Invite: require('./invite.js'),
    Bi: require('./bi.js'),
    Stats: require('./stats.js'),
    Mcsrv: require('./mcsrv.js'),
    Mcsrvapi: require('./mcsrvapi.js'),
    ServidoresDS: require('./servidores.js'),
    Rol: require('./roles.js'),
    Csgo: require('./statscs.js'),
    Rolinfo: require('./rolinfo.js'),
    Abrazo: require('./abrazo.js'),
    Beso: require('./beso.js'),
    Ping: require('./ping.js'),
    Caricia: require('./caricia.js'),
    Lamida: require('./lamida.js'),
    Sopapo: require('./sopapo.js'),
    Serverinfo: require('./serverinfo.js'),
    Miembros: require('./miembros.js'),
    Ban: require('./ban.js'),
    Otaku: require('./otaku.js'),
    Trapo: require('./trapo.js'),
    Support: require('./bot/support.js')
};
