module.exports = {
    100: require('./100.js'),
    Avatar: require('./avatar.js'),
    BastaChicos: require('./bastachicos.js'),
    Calmese: require('./calmese.js'),
    Eu: require('./eu.js'),
    Furry: require('./furry.js'),
    Gay: require('./gay.js'),
    Help: require('./help.js'),
    Invite: require('./invite.js'),
    Otaku: require('./otaku.js'),
    Ping: require('./ping.js'),
    Play: require('./play.js'),
    Skip: require('./skip.js'),
    Stop: require('./stop.js'),
    Puto: require('./puto.js'),
    Up: require('./up.js'),
    Cague: require('./cague.js'),
    Web: require('./web.js'),
    Boda: require('./boda.js')
};
